apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mf7j6x5r8-java-quarkus
  janus-idp.io/tekton: mf7j6x5r8-java-quarkus
  backstage.io/kubernetes-id: mf7j6x5r8-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mf7j6x5r8-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
